# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APTDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democonfig',
            name='idc_1_time',
            field=models.IntegerField(verbose_name='IDC 1 Scans per hour'),
        ),
        migrations.AlterField(
            model_name='democonfig',
            name='idc_2_time',
            field=models.IntegerField(verbose_name='IDC 2 Scans per hour'),
        ),
        migrations.AlterField(
            model_name='democonfig',
            name='idc_3_time',
            field=models.IntegerField(verbose_name='IDC 3 Scans per hour'),
        ),
        migrations.AlterField(
            model_name='democonfig',
            name='idc_4_time',
            field=models.IntegerField(verbose_name='IDC 4 Scans per hour'),
        ),
    ]
