# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APTDemo', '0002_auto_20160818_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='democonfig',
            name='jdf_input_path',
            field=models.CharField(default='C:/APTApplication/Server/Inputs/JDFInput', max_length=200, verbose_name='JIF Input Folder'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='jif_acks_path',
            field=models.CharField(default='C:/APTApplication/Server/Inputs/JIFAcks', max_length=200, verbose_name='JIF ACKs Folder'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='proc_phase_path',
            field=models.CharField(default='C:/APTApplication/Server/Outputs/WIP', max_length=200, verbose_name='Processing Phase XML Folder'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='reprint_path',
            field=models.CharField(default='C:/APTApplication/Server/Outputs/ReprintFiles', max_length=200, verbose_name='Reprint Folder'),
        ),
    ]
