# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APTDemo', '0004_auto_20160822_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democonfig',
            name='idc_1_multi',
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_1_ps',
            field=models.CharField(default='sheet', max_length=5, verbose_name='IDC 1 piece or sheet'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_2_ps',
            field=models.CharField(default='sheet', max_length=5, verbose_name='IDC 2 piece or sheet'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_3_ps',
            field=models.CharField(default='piece', max_length=5, verbose_name='IDC 3 piece or sheet'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_4_ps',
            field=models.CharField(default='piece', max_length=5, verbose_name='IDC 4 piece or sheet'),
        ),
    ]
